# Generated by Django 5.1.5 on 2025-02-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
